#!/usr/bin/env bash
# a bash script to configure Nginx to have a custom 404 page
# conatining a string "Ceci n'est pas une page"

sudo apt-get update -y -qq
sudo apt-get install -y nginx -qq
echo "Hello World!" > index.nginx-debian.html
sudo mv index.nginx-debian.html /var/www/html

echo "Ceci n'est pas une page" > 404_page.html
sudo mv 404_page.html /var/www/html

echo "
   #
   
   server {
   listen 80 default_server;
   listen [::]:80 default_server;
   
   root /var/www/html;
   index index.nginx-debian.html index.html;
   location /redirect_me {
      return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
   }
   error_page 404 /404_page.html;
   location = /404_page.html{
      internal;
   }
}" > default

sudo mv -f default /etc/nginx/sites-available/default
sudo service nginx restart
