#!/usr/bin/env bash
# a bash script that fix ubuntu container's installation of nginx
# form listening on port 80

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
