#!/usr/bin/env bash
# a bash script that fix intallation of nginx in an ubuntu container from listening on
# port 80, and making it as small as possible
echo -e "sed -iE 's/listen 8080/listen 80/g' /etc/nginx/sites-enabled/default\
sed -i 's/listen \[::\]:8080/listen \[::\]:80/g' /etc/nginx/sites-enabled/default\n
pgrep nginx -o > /run/nginx.pid\nnginx -s reload\necho''> /run/nginx.pid" | bash
