#!/usr/bin/env bash
#creats a file in a path containing its PID
#display a string indefinite  and handle a SIGTERM and SIGINT signal
#delete the file created on SIGQUIT OR SIGTERM

handle_sigterm()
{
    rm /var/run/myscript.pid
    exit
}

echo "$$" > /var/run/myscript.pid

while true
do
    echo "To infinity and beyond"
    trap 'echo "I hate the kill command"' SIGTERM
    trap 'echo "Y U no love me?!"' SIGINT
    trap 'handle_sigterm' SIGTERM || SIGQUIT
    sleep 2
done
