#!/usr/bin/env bash
# a script that manages manage_my_process(script)

if [ "start" == "$1" ]
then
    ./manage_my_process & echo $$ > /var/run/my_process.pid
    echo "manage_my_process started"
elif [ "stop" == "$1" ]
then
    kill "$(pgrep -f /manage_my_process)"
    rm /var/run/my_process.pid
    echo "manage_my_process stopped"
elif [ "restart" == "$1" ]
then
     kill "$(pgrep -f /manage_my_process)"
     rm /var/run/my_process.pid
     ./manage_my_process & echo "manage_my_process restarted"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
