#!/bin/bash
#a Bash script that kills the process 7-highlander
# Use pkill to find the PID of the process based on its name
pid=$(pgrep -f "7-highlander")

if [ -n "$pid" ]; then
    kill -9 "$pid"
    echo "Killed"
fi
