#!/usr/bin/env bash
#it a bash script that display a string 10 times
#+ on the 9th iteration it adds hi
i=1
while [ $i -le 10 ]
do
    if [ $i -eq 9 ]
    then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    ((i++))
done
