#!/usr/bin/env bash
# this is bash script that loop 1 to 10 displayin a string
# diplay bad luck on 4th iteration
# display good luck on 8th iteration

i=1
while [ $i -le 10 ]
do
    if [ $i -eq 4 ]
    then
        echo "bad luck"
    elif [ $i -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((i++))
done
