#!/usr/bin/env bash
# this bash script diplay numbes for 1 to 20
# but diplay 4th iteration bad luck from China
# but diplay 9th iteration bad luck from Japan
# but diplay 17th iteration bad luck from Italy
i=1
while ((i<=20))
do
    echo "$i"
    case $i in
        "4") echo "bad luck from China";;
        "9") echo "bad luck from Japan";;
        "17") echo "bad luck from Italy";;
    esac
    ((i++))
done
