#!/usr/bin/env bash
# a script that allows a conatiner to run nginx as nginx user  
chmod ugo+wrx /etc/apache2/ports.conf /etc/nginx/nginx.conf
sed -i 's/Listen 8080/#Listen 8080/g' /etc/apache2/ports.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
pkill -1 apache2
sudo -u nginx service nginx restart
